<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace reservedseating;

use \maglev\MagLevString;
use \maglev\MagLevFunction;
use \php\Boot;
use \maglev\MagLevResult;
use \maglev\MagLev;
use \maglev\MagLevError;
use \maglev\MagLevArray;

class ReservedSeating {
	/**
	 * @var MagLev
	 */
	public $maglev;

	/**
	 * @param MagLev $maglev
	 * 
	 * @return void
	 */
	public function __construct ($maglev) {
		#/src/reservedseating/ReservedSeating.hx:12: characters 3-23
		$this->maglev = $maglev;
		#/src/reservedseating/ReservedSeating.hx:13: characters 3-22
		$this->registerMyMethods();
	}

	/**
	 * @return void
	 */
	public function registerMyMethods () {
		#/src/reservedseating/ReservedSeating.hx:17: characters 3-25
		$bus = $this->maglev;
		#/src/reservedseating/ReservedSeating.hx:19: lines 19-28
		$this->maglev->register("ReservedSeating.CreateVenue", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:20: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:21: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:22: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.CreateVenue"));
			#/src/reservedseating/ReservedSeating.hx:23: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:24: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:25: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CreateVenue' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:26: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:27: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:30: lines 30-39
		$this->maglev->register("ReservedSeating.CreateVenueConfiguration", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:31: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:32: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:33: characters 4-82
			$data->push(MagLevString::fromString("ReservedSeating.CreateVenueConfiguration"));
			#/src/reservedseating/ReservedSeating.hx:34: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:35: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:36: characters 4-238
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CreateVenueConfiguration' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:37: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:38: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:41: lines 41-50
		$this->maglev->register("ReservedSeating.CreateSeat", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:42: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:43: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:44: characters 4-68
			$data->push(MagLevString::fromString("ReservedSeating.CreateSeat"));
			#/src/reservedseating/ReservedSeating.hx:45: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:46: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:47: characters 4-224
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CreateSeat' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:48: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:49: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:52: lines 52-61
		$this->maglev->register("ReservedSeating.CreateEvent", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:53: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:54: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:55: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.CreateEvent"));
			#/src/reservedseating/ReservedSeating.hx:56: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:57: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:58: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CreateEvent' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:59: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:60: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:63: lines 63-72
		$this->maglev->register("ReservedSeating.CreateTable", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:64: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:65: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:66: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.CreateTable"));
			#/src/reservedseating/ReservedSeating.hx:67: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:68: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:69: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CreateTable' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:70: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:71: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:74: lines 74-83
		$this->maglev->register("ReservedSeating.CreateOrder", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:75: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:76: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:77: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.CreateOrder"));
			#/src/reservedseating/ReservedSeating.hx:78: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:79: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:80: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CreateOrder' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:81: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:82: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:85: lines 85-94
		$this->maglev->register("ReservedSeating.GetVenue", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:86: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:87: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:88: characters 4-66
			$data->push(MagLevString::fromString("ReservedSeating.GetVenue"));
			#/src/reservedseating/ReservedSeating.hx:89: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:90: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:91: characters 4-222
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetVenue' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:92: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:93: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:96: lines 96-105
		$this->maglev->register("ReservedSeating.GetVenueConfiguration", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:97: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:98: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:99: characters 4-79
			$data->push(MagLevString::fromString("ReservedSeating.GetVenueConfiguration"));
			#/src/reservedseating/ReservedSeating.hx:100: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:101: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:102: characters 4-235
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetVenueConfiguration' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:103: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:104: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:107: lines 107-116
		$this->maglev->register("ReservedSeating.GetSeat", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:108: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:109: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:110: characters 4-65
			$data->push(MagLevString::fromString("ReservedSeating.GetSeat"));
			#/src/reservedseating/ReservedSeating.hx:111: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:112: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:113: characters 4-221
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetSeat' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:114: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:115: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:118: lines 118-127
		$this->maglev->register("ReservedSeating.GetEvent", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:119: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:120: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:121: characters 4-66
			$data->push(MagLevString::fromString("ReservedSeating.GetEvent"));
			#/src/reservedseating/ReservedSeating.hx:122: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:123: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:124: characters 4-222
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetEvent' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:125: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:126: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:129: lines 129-138
		$this->maglev->register("ReservedSeating.GetTable", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:130: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:131: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:132: characters 4-66
			$data->push(MagLevString::fromString("ReservedSeating.GetTable"));
			#/src/reservedseating/ReservedSeating.hx:133: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:134: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:135: characters 4-222
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetTable' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:136: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:137: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:140: lines 140-149
		$this->maglev->register("ReservedSeating.UpdateVenue", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:141: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:142: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:143: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.UpdateVenue"));
			#/src/reservedseating/ReservedSeating.hx:144: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:145: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:146: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.UpdateVenue' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:147: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:148: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:151: lines 151-160
		$this->maglev->register("ReservedSeating.UpdateVenueConfiguration", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:152: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:153: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:154: characters 4-82
			$data->push(MagLevString::fromString("ReservedSeating.UpdateVenueConfiguration"));
			#/src/reservedseating/ReservedSeating.hx:155: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:156: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:157: characters 4-238
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.UpdateVenueConfiguration' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:158: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:159: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:162: lines 162-171
		$this->maglev->register("ReservedSeating.UpdateSeat", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:163: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:164: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:165: characters 4-68
			$data->push(MagLevString::fromString("ReservedSeating.UpdateSeat"));
			#/src/reservedseating/ReservedSeating.hx:166: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:167: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:168: characters 4-224
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.UpdateSeat' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:169: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:170: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:173: lines 173-182
		$this->maglev->register("ReservedSeating.UpdateEvent", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:174: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:175: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:176: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.UpdateEvent"));
			#/src/reservedseating/ReservedSeating.hx:177: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:178: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:179: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.UpdateEvent' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:180: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:181: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:184: lines 184-193
		$this->maglev->register("ReservedSeating.UpdateTable", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:185: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:186: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:187: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.UpdateTable"));
			#/src/reservedseating/ReservedSeating.hx:188: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:189: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:190: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.UpdateTable' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:191: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:192: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:195: lines 195-204
		$this->maglev->register("ReservedSeating.DeleteVenue", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:196: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:197: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:198: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.DeleteVenue"));
			#/src/reservedseating/ReservedSeating.hx:199: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:200: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:201: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.DeleteVenue' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:202: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:203: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:206: lines 206-215
		$this->maglev->register("ReservedSeating.DeleteVenueConfiguration", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:207: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:208: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:209: characters 4-82
			$data->push(MagLevString::fromString("ReservedSeating.DeleteVenueConfiguration"));
			#/src/reservedseating/ReservedSeating.hx:210: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:211: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:212: characters 4-238
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.DeleteVenueConfiguration' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:213: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:214: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:217: lines 217-226
		$this->maglev->register("ReservedSeating.DeleteSeat", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:218: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:219: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:220: characters 4-68
			$data->push(MagLevString::fromString("ReservedSeating.DeleteSeat"));
			#/src/reservedseating/ReservedSeating.hx:221: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:222: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:223: characters 4-224
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.DeleteSeat' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:224: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:225: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:228: lines 228-237
		$this->maglev->register("ReservedSeating.DeleteEvent", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:229: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:230: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:231: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.DeleteEvent"));
			#/src/reservedseating/ReservedSeating.hx:232: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:233: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:234: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.DeleteEvent' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:235: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:236: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:239: lines 239-248
		$this->maglev->register("ReservedSeating.DeleteTable", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:240: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:241: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:242: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.DeleteTable"));
			#/src/reservedseating/ReservedSeating.hx:243: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:244: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:245: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.DeleteTable' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:246: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:247: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:250: lines 250-259
		$this->maglev->register("ReservedSeating.DeleteOrder", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:251: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:252: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:253: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.DeleteOrder"));
			#/src/reservedseating/ReservedSeating.hx:254: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:255: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:256: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.DeleteOrder' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:257: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:258: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:261: lines 261-270
		$this->maglev->register("ReservedSeating.CompleteOrder", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:262: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:263: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:264: characters 4-71
			$data->push(MagLevString::fromString("ReservedSeating.CompleteOrder"));
			#/src/reservedseating/ReservedSeating.hx:265: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:266: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:267: characters 4-227
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CompleteOrder' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:268: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:269: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:272: lines 272-281
		$this->maglev->register("ReservedSeating.AddSeatToOrder", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:273: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:274: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:275: characters 4-72
			$data->push(MagLevString::fromString("ReservedSeating.AddSeatToOrder"));
			#/src/reservedseating/ReservedSeating.hx:276: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:277: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:278: characters 4-228
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.AddSeatToOrder' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:279: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:280: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:283: lines 283-292
		$this->maglev->register("ReservedSeating.ContinueOrder", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:284: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:285: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:286: characters 4-71
			$data->push(MagLevString::fromString("ReservedSeating.ContinueOrder"));
			#/src/reservedseating/ReservedSeating.hx:287: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:288: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:289: characters 4-227
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.ContinueOrder' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:290: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:291: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:294: lines 294-303
		$this->maglev->register("ReservedSeating.AutoSelect", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:295: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:296: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:297: characters 4-68
			$data->push(MagLevString::fromString("ReservedSeating.AutoSelect"));
			#/src/reservedseating/ReservedSeating.hx:298: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:299: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:300: characters 4-224
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.AutoSelect' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:301: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:302: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:305: lines 305-314
		$this->maglev->register("ReservedSeating.CancelEvent", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:306: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:307: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:308: characters 4-69
			$data->push(MagLevString::fromString("ReservedSeating.CancelEvent"));
			#/src/reservedseating/ReservedSeating.hx:309: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:310: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:311: characters 4-225
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CancelEvent' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:312: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:313: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:316: lines 316-325
		$this->maglev->register("ReservedSeating.CancelReservation", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:317: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:318: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:319: characters 4-75
			$data->push(MagLevString::fromString("ReservedSeating.CancelReservation"));
			#/src/reservedseating/ReservedSeating.hx:320: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:321: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:322: characters 4-231
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.CancelReservation' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:323: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:324: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:327: lines 327-336
		$this->maglev->register("ReservedSeating.GetSeatsAndTablesForEvent", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:328: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:329: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:330: characters 4-83
			$data->push(MagLevString::fromString("ReservedSeating.GetSeatsAndTablesForEvent"));
			#/src/reservedseating/ReservedSeating.hx:331: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:332: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:333: characters 4-239
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetSeatsAndTablesForEvent' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:334: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:335: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:338: lines 338-347
		$this->maglev->register("ReservedSeating.FindAbandonedOrders", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:339: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:340: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:341: characters 4-77
			$data->push(MagLevString::fromString("ReservedSeating.FindAbandonedOrders"));
			#/src/reservedseating/ReservedSeating.hx:342: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:343: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:344: characters 4-233
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.FindAbandonedOrders' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:345: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:346: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:349: lines 349-358
		$this->maglev->register("ReservedSeating.GetOrdersForUser", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:350: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:351: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:352: characters 4-74
			$data->push(MagLevString::fromString("ReservedSeating.GetOrdersForUser"));
			#/src/reservedseating/ReservedSeating.hx:353: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:354: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:355: characters 4-230
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetOrdersForUser' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:356: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:357: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:360: lines 360-369
		$this->maglev->register("ReservedSeating.GetAllEventsOnSale", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:361: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:362: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:363: characters 4-76
			$data->push(MagLevString::fromString("ReservedSeating.GetAllEventsOnSale"));
			#/src/reservedseating/ReservedSeating.hx:364: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:365: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:366: characters 4-232
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetAllEventsOnSale' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:367: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:368: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:371: lines 371-380
		$this->maglev->register("ReservedSeating.UpdateVenueConfigurationAvailability", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:372: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:373: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:374: characters 4-94
			$data->push(MagLevString::fromString("ReservedSeating.UpdateVenueConfigurationAvailability"));
			#/src/reservedseating/ReservedSeating.hx:375: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:376: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:377: characters 4-250
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.UpdateVenueConfigurationAvailability' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:378: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:379: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:382: lines 382-391
		$this->maglev->register("ReservedSeating.GetVenueConfigurations", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:383: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:384: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:385: characters 4-80
			$data->push(MagLevString::fromString("ReservedSeating.GetVenueConfigurations"));
			#/src/reservedseating/ReservedSeating.hx:386: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:387: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:388: characters 4-236
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetVenueConfigurations' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:389: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:390: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:393: lines 393-402
		$this->maglev->register("ReservedSeating.GetOrderSummary", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:394: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:395: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:396: characters 4-73
			$data->push(MagLevString::fromString("ReservedSeating.GetOrderSummary"));
			#/src/reservedseating/ReservedSeating.hx:397: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:398: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:399: characters 4-229
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetOrderSummary' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:400: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:401: characters 4-17
			return $result;
		}));
		#/src/reservedseating/ReservedSeating.hx:404: lines 404-413
		$this->maglev->register("ReservedSeating.GetAllVenuesByOwner", MagLevFunction::fromFunction(function ($args) use (&$bus) {
			#/src/reservedseating/ReservedSeating.hx:405: characters 4-48
			$data = MagLevArray::create();
			#/src/reservedseating/ReservedSeating.hx:406: characters 4-59
			$data->push(MagLevString::fromString("_not_implemented_"));
			#/src/reservedseating/ReservedSeating.hx:407: characters 4-77
			$data->push(MagLevString::fromString("ReservedSeating.GetAllVenuesByOwner"));
			#/src/reservedseating/ReservedSeating.hx:408: characters 4-57
			$data->push(MagLevString::fromString("reservedseating"));
			#/src/reservedseating/ReservedSeating.hx:409: characters 4-48
			$bus->call("MindPowered.Telemetry.Send", $data);
			#/src/reservedseating/ReservedSeating.hx:410: characters 4-233
			$err = MagLevError::create(-20000, "You are trying to use the 'ReservedSeating.GetAllVenuesByOwner' method but it's not quite done yet. Please email support@mindpowered.dev to find out when it will be done.", $data);
			#/src/reservedseating/ReservedSeating.hx:411: characters 4-58
			$result = MagLevResult::fromError($err);
			#/src/reservedseating/ReservedSeating.hx:412: characters 4-17
			return $result;
		}));
	}
}

Boot::registerClass(ReservedSeating::class, 'reservedseating.ReservedSeating');
